### ISSUE TITLE
[BUG] innr SP120 only updates energy consumption on HA restart

### ISSUE THREAD

**Issue by macmeck** [zigpy/zha-device-handlers#4652]
### Bug description

The innr SP120 does not update the total energy consumption sensor in HA on a regular basis any more. Looks like the value stays constant over the runtime of Home Assistant, even when I unplug and restart the device. There is not a communication error as I can see other sensors, i.e. current power consumption, being updated live.
Only after restarting Home Assistant, the value for energy consumption is being updated for the sensor. 

This used to work before, so I think the current behaviour is due to some recent changes.

### Steps to reproduce

1. set up device and monitor sensor
2. consume notable amount of energy through the device, which should trigger updates
3. see the value of energy sensor remain constant
4. restart Home Assistant
5. see a jump in sensor as it receives and displays the updated and current value

### Expected behavior

live change of the energy consumption sensor as energy is being consumed

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

<img width="567" height="351" alt="Image" src="https://github.com/user-attachments/assets/1935e7ce-6c96-4927-837e-5964f1e9728b" />

</details>

### Diagnostics information

[zha-a970713c1d76c0d05915b95c74dc4c5d-innr SP 120-cde3852a2a70a3eeb578c928b196dc8a.json](https://github.com/user-attachments/files/24613296/zha-a970713c1d76c0d05915b95c74dc4c5d-innr.SP.120-cde3852a2a70a3eeb578c928b196dc8a.json)

### Device signature

<details><summary>Device signature</summary>

```json

{
  "node_descriptor": {
    "logical_type": 1,
    "complex_descriptor_available": 0,
    "user_descriptor_available": 0,
    "reserved": 0,
    "aps_flags": 0,
    "frequency_band": 8,
    "mac_capability_flags": 142,
    "manufacturer_code": 4454,
    "maximum_buffer_size": 127,
    "maximum_incoming_transfer_size": 80,
    "server_mask": 0,
    "maximum_outgoing_transfer_size": 80,
    "descriptor_capability_field": 0
  },
  "endpoints": {
    "1": {
      "profile_id": "0xc05e",
      "device_type": "0x0010",
      "input_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x000a",
        "0x0702",
        "0x0b04"
      ],
      "output_clusters": [
        "0x0003",
        "0x000a",
        "0x0019"
      ]
    },
    "2": {
      "profile_id": "0xc05e",
      "device_type": "0x1000",
      "input_clusters": [
        "0x1000"
      ],
      "output_clusters": []
    }
  },
  "manufacturer": "innr",
  "model": "SP 120",
  "class": "zhaquirks.innr.innr_sp120_plug.SP120"
}

```

</details>

### Logs

<details><summary>Logs</summary>

```python

[Paste the logs here]

```

</details>

**Comment by peeter123** [comment]
I am experiencing the same issue with all my INNR SP 120 devices. Only on a restart of Home Assistant (currently 2026.2.3) the values are updated. This started around mid February when I updated form 2026.1.x to 2026.2.x.

**Comment by TheJulianJES** [comment]
Please press the "Reconfigure" button on the ZHA device page. After the reconfiguration, attribute reporting should work again. If you're on the latest firmware, it'll also stay that way.

Also, make sure you're on 2026.2.2 or newer. 2.0 and 2.1 had an issue where attribute reporting wasn't properly set up for new devices.

**Comment by peeter123** [comment]
I have tried this on all my devices and restarted HA afterwards (2026.2.3), unfortunately it is still not working. See attached screenshot, you can also see the step when I restarted HA. It keeps flat while using a 100 W continuously.

<img width="543" height="473" alt="Image" src="https://github.com/user-attachments/assets/c7ed1f94-c7e2-4bc9-9f62-5b6eb4713dd3" />

This is the reconfigure report:
<img width="705" height="1165" alt="Image" src="https://github.com/user-attachments/assets/3dadc2e7-b6f9-40fa-a5f2-267b415ad47e" />
<img width="705" height="1120" alt="Image" src="https://github.com/user-attachments/assets/eae7796c-618b-442e-ad4c-676c652d0239" />

**Comment by TheJulianJES** [comment]
Hmm, interesting. So it's failing to set up reporting for `current_summ_delivered`. Please download and attach device diagnostics (from the device page). I wonder if we're trying to set up reporting for too many attributes now..? That wouldn't be great. I don't know why they're not marked as unsupported on that device...

Also, enable debug logs (Settings -> Devices & services -> ZHA -> three dots in the upper right corner, enable debug logging), then click reconfigure again, and disable debug logs to download. Finally, attach the debug logs here or email them to me (as they might contain some sensitive information). The email is on my GH profile.

**Comment by peeter123** [comment]
Thanks Julian, I send you an email with the debug log. Unfortunately I cannot download device diagnostics because it errors with a 500, maybe something related?

See attached [home-assistant_zha_2026-02-27T20-01-29.035Z_diagnostics_500.txt](https://github.com/user-attachments/files/25613135/home-assistant_zha_2026-02-27T20-01-29.035Z_diagnostics_500.txt)

**Comment by macmeck** [comment]
@TheJulianJES , any additional information required to drive this forward and get the device running properly again?

**Comment by macmeck** [comment]
And there goes another point release without this being fixed or even worked on. Anything we can do about it? It's so annoying as it worked perfectly until one of the more recent releases... thanks

**Comment by peeter123** [comment]
> [@macmeck](https://github.com/macmeck) [@peeter123](https://github.com/peeter123) — one more thing that would help pin this down (separate from testing the [#5053](https://github.com/zigpy/zha-device-handlers/pull/5053) polling fix): a debug log of a **manual read** of `current_summ_delivered`.
> 
> The configure-reporting failure is `INVALID_DATA_TYPE`, which hints the plug may report this attribute with a different ZCL type than the spec's `uint48`. A manual read shows the type the device actually uses — which would tell us whether reporting could be _fixed_ by correcting the type, rather than only worked around by polling. None of the logs so far captured a read of it (the reconfigure only binds + configures reporting; the start-up read was outside the captured window), so a fresh one is needed:
> 
> 1. Enable ZHA debug logging: **Settings → Devices & services → ZHA → ⋮ (top-right three dots) → Enable debug logging** ([HA guide, with screenshots](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging)).
> 2. Open your **Innr SP 120** device page → **⋮ menu (left) → Manage Zigbee device**.
> 3. Select the **Smart Energy Metering** cluster (`0x0702`) — it may be listed under the quirk's cluster class name (e.g. `MeteringClusterInnrOld`).
> 4. In the second (attribute) dropdown, select **`current_summ_delivered`**, then press **Read attribute**.
> 5. Disable debug logging again (same menu) — that downloads the log.
> 
> An extract of the read from the log is enough — the `Read_Attributes_rsp` line for cluster `0x0702` showing the attribute's `TypeValue` type. Otherwise, send the whole debug log to [@TheJulianJES](https://github.com/TheJulianJES) (email on his GitHub profile), like before.
> 
> **Easier alternatives**, if you prefer not to do the manual read: a fresh re-pair — or a **Reconfigure** (on recent HA this now runs a full re-interview) — reads this attribute during the interview, so it shows up in the log on its own. And if you install the [#5053](https://github.com/zigpy/zha-device-handlers/pull/5053) quirk with debug logging enabled, its new background poll reads `current_summ_delivered` every ~30–45 s — so testing that fix also captures the type for us in one go.

[home-assistant_zha_2026-06-03T06-38-37.208Z_manual_read.log](https://github.com/user-attachments/files/28540050/home-assistant_zha_2026-06-03T06-38-37.208Z_manual_read.log)

I have executed the steps described and did a manual read, the attached log file is without the quirk installed (only extracted the zha relevant log items). I will test the quirk next.

When pressing the manual read the current_sum_delivered sensor is updated correctly as well.

**Comment by peeter123** [comment]
The polling custom_quirk for current_summ_delivered in #5053 works correctly, however this is probably a work-around and not fixing the root cause.

**Comment by TheJulianJES** [comment]
@peeter123 Thanks! The log reads for `current_summ_delivered` are for a device where the cluster is called `TuyaZBMeteringCluster`, so that's likely not the Innr plug, but a Tuya plug that's being polled.

Can you get a section like that when reading the attribute on the Innr SP120 plug? If you have the polling quirk installed, you should see a ton of sections like that if you enable debug logs.

**Comment by peeter123** [comment]
@TheJulianJES My apologies, I have send you the full DEBUG log via mail.

I think the relevant entry for the `current_summ_delivered` is in this section:
```2026-06-05 08:48:19.004 DEBUG (MainThread) [bellows.zigbee.application] Received incomingMessageHandler frame with [<EmberIncomingMessageType.INCOMING_UNICAST: 0>, EmberApsFrame(profileId=260, clusterId=1794, sourceEndpoint=1, destinationEndpoint=1, options=<EmberApsOption.APS_OPTION_RETRY|APS_OPTION_ENABLE_ROUTE_DISCOVERY: 320>, groupId=0, sequence=114), 208, -48, 0xF14B, 255, 255, b'\x18\xe6\x01\x00\x00\x00%*\xc6\x01\x00\x00\x00\x00\x02\x00\x18\x00']
2026-06-05 08:48:19.004 DEBUG (MainThread) [zigpy.application] Received a packet: ZigbeePacket(timestamp=datetime.datetime(2026, 6, 5, 6, 48, 19, 4417, tzinfo=datetime.timezone.utc), priority=None, src=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xF14B), src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0x0000), dst_ep=1, source_route=None, extended_timeout=False, tsn=114, profile_id=260, cluster_id=1794, data=Serialized[b'\x18\xe6\x01\x00\x00\x00%*\xc6\x01\x00\x00\x00\x00\x02\x00\x18\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=0, lqi=208, rssi=-48)
2026-06-05 08:48:19.004 DEBUG (MainThread) [zigpy.zcl] [0xF14B:1:0x0702] Received ZCL frame: '18 e6 01 00 00 00 25 2a c6 01 00 00 00 00 02 00 18 00'
2026-06-05 08:48:19.004 DEBUG (MainThread) [zigpy.zcl] [0xF14B:1:0x0702] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl<0x18>(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=0, direction=<Direction.Server_to_Client: 1>, disable_default_response=1, reserved=0, *is_cluster=False, *is_general=True), tsn=230, command_id=1, *direction=<Direction.Server_to_Client: 1>)
2026-06-05 08:48:19.005 DEBUG (MainThread) [zigpy.zcl] [0xF14B:1:0x0702] Decoded ZCL frame: MeteringClusterInnrOld:ReadAttributesResponse(status_records=[ReadAttributeRecord(attrid=0, status=<Status.SUCCESS: 0>, value=TypeValue(type=uint48_t, value=116266)), ReadAttributeRecord(attrid=512, status=<Status.SUCCESS: 0>, value=TypeValue(type=bitmap8, value=<bitmap8: 0>))])
2026-06-05 08:48:19.005 DEBUG (MainThread) [zigpy.event] Emitting event attribute_read with data AttributeReadEvent(event_type='attribute_read', device_ieee='00:15:8d:00:03:1e:fe:a1', endpoint_id=1, cluster_type=<ClusterType.Server: 0>, cluster_id=1794, attribute_name='current_summ_delivered', attribute_id=0, manufacturer_code=None, raw_value=116266, value=116266) (2 listeners)
2026-06-05 08:48:19.005 DEBUG (MainThread) [zha.zigbee.cluster_handlers] [0xF14B:1:0x0702]: cluster_handler[smartenergy_metering] attribute_updated - cluster[MeteringClusterInnrOld] attr[current_summ_delivered] value[116266]```

**Comment by TheJulianJES** [comment]
Thanks. Yeah, so the device uses the correct data type for that attribute. That's also the one zigpy is sending when configuring attribute reporting. There's some sort of firmware bug then if the device rejects it with `INVALID_DATA_TYPE`.

From what I can see, reporting has never worked before. We didn't change anything there. And even if we did, the old reporting config lives on the device, so it would still send data just like before, until it's manually reset and reconfigured.

I can only imagine that there was perhaps an issue in the past where we already manually polled this attribute accidentally? I don't think so, but that's my only guess. (EDIT: Double checked and we should have never polled this plug in the past.)
For anything else, we need debug logs from a HA Core version where reporting was supposedly working. So, full (remove and) re-pair on that older HA version, with debug logs enabled. Then let it sit a while whilst it's consuming energy.

We'll just go with the polling PR, for now.

**Comment by macmeck** [comment]
I am pretty sure that this worked before. Let me see if I can set something up over the next days to validate with an older version.

**Comment by peeter123** [comment]
I agree with @macmeck, it definitely was working before (I think pre 2026.2 or 2026.1), would be great to see if @macmeck can find the version in which it regressed.

**Comment by macmeck** [comment]
I cannot pin down the exact version but I have restored a 2025.11 version into a test system where it's updating regularly. The latest change on SP120 quirk was #4592 on 04 Jan 2026. maybe a hint?

@TheJulianJES what can I provide from my test system for debugging purposes?

**Comment by TheJulianJES** [comment]
Interesting! That change shouldn't be related. Please enable debug logs for ZHA per https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging. Then wait a bit until the summation updates. Afterwards, please also reconfigure the device on that version through the UI (whilst debug logs are still enabled).

At the end, you can disable debug logs via the UI, and HA should prompt you to download the HA log file automatically. Please send me the entire log file via email (or Discord) found on my GitHub profile (they could contain some slightly sensitive information, but generally shouldn't). You can also upload it here instead if you're comfortable with that.

**Comment by macmeck** [comment]
ok, I sent you the debug logs via mail. If I can provide anything else, please let me know!

**Comment by TheJulianJES** [comment]
@macmeck Thanks for the logs. They were really helpful! Like the bot mentioned above, the device does report that attribute every 30 minutes (without the setup of attribute reporting for that ever succeeding).

This wasn't caught in the previous log file, as that wasn't 30 minutes long 😅.

But it reports that ZCL attribute with the manufacturer-specific bit set! That's a firmware issue, or a really weird implementation on Innr's side if they have both a ZCL and manufacturer-specific attribute with the same attribute ID, with only the latter being automatically reported by the device.

Recent zigpy versions did indeed fix an issue where a manufacturer-specific attribute with the same ID as a ZCL one would conflict. Up until now, we had no negative side effects reported by that change – only positive ones, as Frient and Ubisys devices often have both ZCL attributes and manufacturer-specific ones with the same ID. Those collided before and caused weird attribute update issues.

But as this plug sends the `current_summation_delivered` attribute with the manufacturer-bit set, we never parse that report for the ZCL attribute. We can fix this in a quirk, so we don't need the polling then. I guess we can either strip the manufacturer bit from the raw ZCL frame, or also define the manufacturer-specific attribute in the custom quirk, and then have that manufacturer-specific attribute being updated also update the ZCL one. I'll take a look at that.

**Comment by TheJulianJES** [comment]
Ah, looks like I forgot to link the new quirk here. Please test the following as a custom quirk. It's https://github.com/zigpy/zha-device-handlers/pull/5082, but that PR may be updated later for some refactoring changes, where it'll only work with HA Core 2026.7.0 and newer (beta releasing today).

If you've tested it, please ping me, so I don't miss this.

<details><summary>Code to paste into a innr_custom_quirk.py file (CLICK TO EXPAND)</summary>
<p>

```python
"""Innr SP 120 plug."""

from zigpy.profiles import zll
from zigpy.quirks import CustomDevice
import zigpy.types as t
from zigpy.zcl import AttributeReportedEvent
from zigpy.zcl.clusters.general import (
    Basic,
    Groups,
    Identify,
    LevelControl,
    OnOff,
    Ota,
    Scenes,
    Time,
)
from zigpy.zcl.clusters.homeautomation import ElectricalMeasurement
from zigpy.zcl.clusters.lightlink import LightLink
from zigpy.zcl.clusters.smartenergy import Metering
from zigpy.zcl.foundation import ZCLAttributeDef

from zhaquirks.const import (
    DEVICE_TYPE,
    ENDPOINTS,
    INPUT_CLUSTERS,
    MODELS_INFO,
    OUTPUT_CLUSTERS,
    PROFILE_ID,
)
from zhaquirks.innr import (
    INNR,
    ElectricalMeasurementClusterInnr,
    MeteringClusterInnrOld,
)


class MeteringClusterInnrSP120(MeteringClusterInnrOld):
    """SP 120 metering that recovers the manufacturer-framed summation report.

    The firmware reports the standard ``current_summ_delivered`` (0x0000) with
    the manufacturer-specific bit set (Innr code 0x1166), so zigpy drops it
    instead of applying it to the ZCL attribute. Define the attribute the device
    reports and mirror its value onto the standard ZCL attribute.
    """

    class AttributeDefs(Metering.AttributeDefs):
        """Metering attributes plus the manufacturer-specific summation reported."""

        current_summ_delivered_mfg = ZCLAttributeDef(
            id=0x0000,
            type=t.uint48_t,
            manufacturer_code=0x1166,
        )

    def __init__(self, *args, **kwargs) -> None:
        """Listen for the manufacturer-specific summation reports."""
        super().__init__(*args, **kwargs)
        self.on_event(AttributeReportedEvent.event_type, self._mirror_summation)

    def _mirror_summation(self, event: AttributeReportedEvent) -> None:
        """Mirror the manufacturer-specific summation onto the ZCL attribute."""
        if event.attribute_name == self.AttributeDefs.current_summ_delivered_mfg.name:
            self.update_attribute(
                Metering.AttributeDefs.current_summ_delivered, event.value
            )


class SP120(CustomDevice):
    """Innr SP 120 smart plug."""

    signature = {
        MODELS_INFO: [(INNR, "SP 120")],
        ENDPOINTS: {
            1: {
                PROFILE_ID: zll.PROFILE_ID,
                DEVICE_TYPE: zll.DeviceType.ON_OFF_PLUGIN_UNIT,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    ElectricalMeasurement.cluster_id,
                    Groups.cluster_id,
                    Identify.cluster_id,
                    LevelControl.cluster_id,
                    Metering.cluster_id,
                    OnOff.cluster_id,
                    Scenes.cluster_id,
                    Time.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                    Identify.cluster_id,
                    Ota.cluster_id,
                    Time.cluster_id,
                ],
            },
            2: {
                PROFILE_ID: zll.PROFILE_ID,
                DEVICE_TYPE: 0x1000,
                INPUT_CLUSTERS: [
                    LightLink.cluster_id,
                ],
                OUTPUT_CLUSTERS: [],
            },
        },
    }

    replacement = {
        ENDPOINTS: {
            1: {
                PROFILE_ID: zll.PROFILE_ID,
                DEVICE_TYPE: zll.DeviceType.ON_OFF_PLUGIN_UNIT,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    ElectricalMeasurementClusterInnr,
                    Groups.cluster_id,
                    Identify.cluster_id,
                    LevelControl.cluster_id,
                    MeteringClusterInnrSP120,
                    OnOff.cluster_id,
                    Scenes.cluster_id,
                    Time.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                    Identify.cluster_id,
                    Ota.cluster_id,
                    Time.cluster_id,
                ],
            },
            2: {
                PROFILE_ID: zll.PROFILE_ID,
                DEVICE_TYPE: 0x1000,
                INPUT_CLUSTERS: [
                    LightLink.cluster_id,
                ],
                OUTPUT_CLUSTERS: [],
            },
        },
    }
```

</p>
</details>

**Comment by macmeck** [comment]
Thanks @TheJulianJES 

I applied the quirk and it's being picked up by HomeAssistant (version 2026.6.4). But still no change in behaviour... do I need to somehow reconfigure the device?

**Comment by macmeck** [comment]
hm, the one in my test environment seems to update now while the other one is still stuck. let me investigate further.

**Comment by macmeck** [comment]
@TheJulianJES  it's totally strange: in my test environment, both my SP120 work correctly and do push the updates into HomeAssistant. If I connect them in to my production network, they don't. Both on 2026.6.4, both indicate to be using the quirk.

I already tried to remove the device from HomeAssistant and the Zigbee network and then re-paired. No change.

one thing: after I re-paired the device, the custom settings (entity names, icons, ...) had been picked up again automatically. Maybe some other legacy settings survived as well? Is there a way to really fully wipe the device configuration from the HomeAssistant instance?

@peeter123 , did you have the chance to test the quirk?

**Comment by MattWestb** [comment]
@macmeck If deleting one device HA is keeping its in device cash (i think for around one minute).
Best is deleting the device and restart HA and then HA is stable adding it and it shall being new (lost old device name and using factory ones).

**Comment by macmeck** [comment]
Not really. I removed it, restarted, waited for one hour before re-pairing. But it still recognizes the device.

**Comment by TheJulianJES** [comment]
Removing the device and then re-pairing it is enough to wipe the entire state. Doing a reconfiguration through HA also fully wipes the state and starts a re-interview since a few releases now. (An OTA firmware update also schedules a re-interview if the devices checks-in shortly afterwards.)

Are you sure the custom quirk is applying correctly? Only 2026.7.0 and newer properly show that in the UI. 2026.6.x and before just show `CustomDeviceV2` for all v2 quirks, and the quirk class for all v1 quirks.

Make sure your `configuration.yaml` for the custom quirk loading is identical. Otherwise, enable debug logs, wait just a bit over an hour, and send them to me via email or Discord (found on my profile). 

---

> one thing: after I re-paired the device, the custom settings (entity names, icons, ...) had been picked up again automatically. Maybe some other legacy settings survived as well? Is there a way to really fully wipe the device configuration from the HomeAssistant instance?

That is HA state. There's no way to disable this, unfortunately. It keeps track of all deleted entities in `.storage` and then the entity registry file. It's separate from Zigbee state though.

**Comment by macmeck** [comment]
At least the device page is showing that it's using the quirk.

Is the quirk expected to work with 2026.7.0? I think you mentioned changes to be required for the new release? If not, then I would quickly trigger the update.

**Comment by TheJulianJES** [comment]
[The PR](https://github.com/zigpy/zha-device-handlers/pull/5082) has been updated with the new imports used by the recent ZHA/quirks refactor, so you can use the quirks file form that PR as a custom quirk.

Otherwise, the custom quirks file with the older imports should also still work – it may just log warnings because of the old imports.

**Comment by macmeck** [comment]
@TheJulianJES , I just sent you the latest debug logs via email. Curious if we can find anything...

**Comment by TheJulianJES** [comment]
It looks like that plug just isn't sending any `current_summ_delivered` reports at all. Interestingly enough, the startup read also seems to show that the value internally is still `0`, so maybe it's just not counting, hence never sending any reports?

(Do note that the "Multiple definitions exist for attribute ID 0x0000" errors in the logs are caused when trying to read the attribute through the web UI (when multiple definitions with the same ID exist) – that needs to be fixed separately.)

What happens if you try the polling quirk instead (https://github.com/zigpy/zha-device-handlers/pull/5053), or remove all quirks, and then manually read the attribute through the web UI? Does it always return `0` or the correct number? (thus also updating the sensor entity then)

**Comment by macmeck** [comment]
Okay, the `0` value can be explained: I just recently re-paired the plug, which resets the value. Never restarted the system since, so this just shows the fact that the value does not update. After I restarted HomeAssistant, it gives a value.

With the quirk applied, there is no `current_summ_delivered` available, only `current_summ_delivered_mfg`:

<img width="473" height="386" alt="Image" src="https://github.com/user-attachments/assets/754ecf28-d5fd-4885-bbab-31b0c7c57f4d" />


Reading this value through the web UI fails.


With the quirk **removed**, I can see the `current_summ_delivered` attribute and can read it through web UI:

<img width="473" height="386" alt="Image" src="https://github.com/user-attachments/assets/78264e27-0e88-4d20-9f90-9c27d653722d" />


If I apply the quirk from https://github.com/zigpy/zha-device-handlers/tree/09b45a62384de4adce55877057cdc910f0e2104c/zhaquirks/innr instead, it looks like it is not being picked up, so I cannot test. Am I missing something here?

<img width="327" height="223" alt="Image" src="https://github.com/user-attachments/assets/febbf133-0cf8-4eee-9975-c6395175bbfe" />


Last but not least on "Multiple definitions exist for attribute ID 0x0000": could this point to some issue in my setup? As indicated before, I am also not able to **fully** remove the device and then re-pair it with no trace to the previous installation. Whenever I reconnect the device, it picks up entity names, icons, ... from before. Even after rebooting HomeAssistant in between, waiting for 24 before re-pairing, ...

**Comment by macmeck** [comment]
@TheJulianJES , just validated in the test environment (where everything is working fine), with the quirk applied, there also is no `current_summ_delivered`, but only `current_summ_delivered_mfg`. Also there, I cannot retrieve `current_summ_delivered_mfg` through the web UI.

**Comment by TheJulianJES** [comment]
Ah yes, both issues are expected. The web UI needs to be updated. It only keys by IDs. You may be able to provide the manufacturer code to further specify which of the two attributes you wanna read, but I think there's no way to provide `None`/`-1`/`0`, so you can only try to read the manufacturer one there if you enter the Innr manufacturer code. Can be found in the simple descriptor (signature or diagnostics). If you want to read the ZCL one through the web UI, you'll currently need to uninstall the quirk.

Either way, it's only a web UI issue. We should also still read the ZCL one on startup.

**Comment by macmeck** [comment]
@TheJulianJES , did the last logs I sent via mail reveal anything? They should contain a value read  >0 at startup.

**Comment by TheJulianJES** [comment]
What coordinators are you using on your different networks (and which firmware versions)? This may only be an issue with the old TI/Z-Stack version you're running, but not with the SiLabs/EZSP coordinator.

See the bot comment below. It's kinda interesting what's (supposedly) happening (plug has a ZLL profile endpoint but actually sends reports with the ZHA profile, so old Z-Stack versions drop them).

**Comment by macmeck** [comment]
Well spotted and thanks for pointing this out. Indeed, with an updated firmware of the coordinator (and with the quirk applied), everything seems to be working fine! Energy consumption is updating now while Home Assistant is running.

So I hope from here, we are good to get this change merged into the code and make the quirk obsolete in future releases.

Thanks for all your efforts and your constant support @TheJulianJES

**Comment by peeter123** [comment]
I have tested #5082 as well and confirm this is working when I use it as custom quirk (replacing the polling one), thanks @TheJulianJES and @macmeck for testing and creating a fix!

I have tested on HA 2026.7.1 with Sonoff Zigbee 3.0 USB Dongle Plus V2
